preliminary visionOS support
LSX-s-Software/PaperPilotApp pull request #26
Opened 2023-11-15 12:59 UTC by MikeWalrus

2023-11-15 15:06 UTC, LSX-s-Software requested changes

2023-11-15 15:06 UTC, LSX-s-Software commented on PaperPilot/Utils/UIKitExtensions.swift
> +#if os(iOS) || os(visionOS)
可以直接改成`#if canImport(UIKit)`

2023-11-15 15:06 UTC, LSX-s-Software commented on PaperPilot/Views/Reader/PaperReader.swift
> +    #endif
这里不需要换行，并且多了个else分支

2023-11-15 15:06 UTC, LSX-s-Software commented on PaperPilot/Views/Reader/PaperReader.swift
> +                        PDFKitThumbnailView(pdfView: pdfView, thumbnailWidth: 125)
这里可以用@Bindable转一次pdfVM之后再用Binding吗，或者能不能直接不用Binding

2023-11-15 15:06 UTC, LSX-s-Software commented on PaperPilot/Info.plist
这个SceneDelegate有用上吗，没有的话可以删掉。
而且好像SwiftUI提供了一种优雅一点的调用SceneDelegate的方法？

2023-11-15 15:55 UTC, MikeWalrus commented on PaperPilot/Views/Reader/PaperReader.swift
> +    #endif
这个现在还有问题 #28

2023-11-15 15:56 UTC, MikeWalrus commented on PaperPilot/Views/Reader/PaperReader.swift
> +                        PDFKitThumbnailView(pdfView: pdfView, thumbnailWidth: 125)
之前试了 应该不行

2023-11-15 15:58 UTC, MikeWalrus commented on PaperPilot/Info.plist
这是抄的别人的，应该可以删掉。只有那个multiple windows有用。xcode不知道为什么和文档上说的不一样，不能在xcode里面直接打勾

2023-11-16 04:13 UTC, LSX-s-Software approved these changes

2023-11-16 04:13 UTC, LSX-s-Software approved these changes

2023-11-16 06:35 UTC, merged